version: "3.9"
services:
  app:
    build: .
    ports:
      - "4000:4000"
    links:
      - dbmysql
  dbmysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER:root
      - MYSQL_ROOT_PASSWORD:123
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
